Traceback (most recent call last):
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 204, in <module>
    main()
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 199, in main
    trainer = DistillationTrainer(config=config)
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 55, in __init__
    self.trainer = self._create_trainer()
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 139, in _create_trainer
    return L.Trainer(
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 395, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 146, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 376, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/accelerators/cuda.py", line 88, in parse_devices
    return _parse_gpu_ids(devices, include_cuda=True)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 102, in _parse_gpu_ids
    return _sanitize_gpu_ids(gpus, include_cuda=include_cuda, include_mps=include_mps)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 135, in _sanitize_gpu_ids
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [0, 1]
 But your machine only has: [0]
Traceback (most recent call last):
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 204, in <module>
    main()
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 199, in main
    trainer = DistillationTrainer(config=config)
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 55, in __init__
    self.trainer = self._create_trainer()
  File "/storage/disk0/arda/dinov2/distillation/train.py", line 139, in _create_trainer
    return L.Trainer(
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 395, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 146, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 376, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/pytorch/accelerators/cuda.py", line 88, in parse_devices
    return _parse_gpu_ids(devices, include_cuda=True)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 102, in _parse_gpu_ids
    return _sanitize_gpu_ids(gpus, include_cuda=include_cuda, include_mps=include_mps)
  File "/home/arda/miniconda3/envs/distillation/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 135, in _sanitize_gpu_ids
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [0, 1]
 But your machine only has: [0]
